
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1.parserLexer.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int SEMICOLON = 2;
  public static final int PLUS = 12;
  public static final int RBRACE = 6;
  public static final int RPAREN = 10;
  public static final int DECIMAL = 17;
  public static final int DIVISION = 14;
  public static final int ETIQUETAS = 25;
  public static final int ERROR = 32;
  public static final int EJECUTAR = 33;
  public static final int LBRACKET = 7;
  public static final int LPAREN = 9;
  public static final int COLON = 3;
  public static final int LBRACE = 5;
  public static final int RBRACKET = 8;
  public static final int PORCENTAJE = 31;
  public static final int TIPO = 27;
  public static final int VALORES = 26;
  public static final int BARRAS = 19;
  public static final int STRING = 11;
  public static final int COMMA = 4;
  public static final int TOTAL = 29;
  public static final int EOF = 0;
  public static final int DEF = 18;
  public static final int PIE = 20;
  public static final int CANTIDAD = 30;
  public static final int EXTRA = 28;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int EJEY = 23;
  public static final int EJEX = 22;
  public static final int INTEGER = 16;
  public static final int UNIR = 24;
  public static final int TITULO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "STRING",
  "PLUS",
  "MINUS",
  "DIVISION",
  "TIMES",
  "INTEGER",
  "DECIMAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "UNIR",
  "ETIQUETAS",
  "VALORES",
  "TIPO",
  "EXTRA",
  "TOTAL",
  "CANTIDAD",
  "PORCENTAJE",
  "ERROR",
  "EJECUTAR"
  };
}

